# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-24 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grunge', '0002_auto_20180224_0837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interview',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='studioexclusive',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='song',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
