# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-24 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grunge', '0004_auto_20180224_0927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='band',
            options={'ordering': ['-timestamp']},
        ),
    ]
