# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-24 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grunge', '0005_auto_20180224_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='file',
            field=models.FileField(default=1, upload_to=b''),
            preserve_default=False,
        ),
    ]
