# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-25 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grunge', '0010_auto_20180225_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='band',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grunge.Band'),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grunge.Album'),
        ),
    ]
