# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-25 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grunge', '0011_auto_20180225_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='album',
            name='width_field',
        ),
        migrations.RemoveField(
            model_name='band',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='band',
            name='width_field',
        ),
        migrations.RemoveField(
            model_name='gig',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='gig',
            name='width_field',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='width_field',
        ),
        migrations.RemoveField(
            model_name='song',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='song',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='band',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='gig',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='interview',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='song',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
