# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-13 06:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grunge', '0012_auto_20180225_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gig',
            name='brief',
        ),
    ]
